### ISSUE TITLE
error in train.py line 160

### ISSUE THREAD

**Issue by yinniyu** [mitroadmaps/roadtracer#10]
I am training roadtracer on some new dataset (East African cities), and I got this error in the train.py file:

> Traceback (most recent call last):
File "train.py", line 160, in <module>
raise Exception('last set has only {} paths, but PARALLEL_PATHS={}'.format(end_idx - start_idx, PARALLEL_PATHS))
Exception: last set has only -948.0 paths, but PARALLEL_PATHS=1024

I followed the instruction on the github page, still get this error

**Comment by uakfdotb** [comment]
Sorry for the slow reply. If you are using python 3 that might be the cause, on this line below the code assumes it will truncate the division:

https://github.com/mitroadmaps/roadtracer/blob/master/roadtracer/train.py#L113

Using python 2 would be easiest solution if that is possible, otherwise I think there are several changes you'd need to make.

**Comment by yinniyu** [comment]
Thank you for the reply. I will try fixing that to see if it will run.
