### ISSUE TITLE
Can you share sample Json file for Starting locations & Pytiles?

### ISSUE THREAD

**Issue by anilbatra2185** [mitroadmaps/roadtracer#15]
Hi,
Thanks for sharing the code for roadtracer. It would be great, if you can share or upload the sample file for each of the followings:

- pytiles.json
- starting_locations.json

I would request you to please let me know the significance of the following terms used in train.py:

- PARALLEL_PATHS
- PARALLEL_TILES
- PATHS_PER_TILE_AXIS

Thanks

**Comment by ErenTuring** [comment]
Hi,
Thanks so much for sharing such valuable work!

Would you like to share how to set the parameters and the contents of the pytiles.json and starting_locations.json to get good prediction results for this data set as follow?
![图片](https://user-images.githubusercontent.com/19544855/61509058-6c592380-aa1f-11e9-984d-ac7391445a06.png)

(Massachusetts Roads Dataset from https://www.cs.toronto.edu/~vmnih/data/?tdsourcetag=s_pctim_aiomsg)

I have to ask you about these codes due to the urgent deadline. I'm sorry for taking up your time.
