### ISSUE TITLE
location of MANUAL_POINT{1,2} in tile

### ISSUE THREAD

**Issue by chrishna1** [mitroadmaps/roadtracer#17]
Hi, Thanks for publishing the implementation of Roadtracer. Its performance is remarkable on the chicago region.

I want to ask : Where does `MANUAL_POINT1` and `MANUAL_POINT2` belongs to in image tiles?
It seems that it must belong to some point in `chicago_-1-2_sat.png`. So I tried locating those two manual points(considering top_left, bottom_left as origin and switching x,y coordinates), but there isn't any road.
![chicago_-1_-2_satgtsmall](https://user-images.githubusercontent.com/26048398/48618242-c56b4600-e9be-11e8-8c62-6ff4a425efaf.png)
Image is rescaled for uploading it on github but I was locating it on original resolution.

**Comment by uakfdotb** [comment]
When actually running it, it should start from many starting locations that are automatically detected by another approach, otherwise if the city has weakly connected components (e.g. separated by river) it may not be able to discover roads in all of the components. I pushed code in this commit https://github.com/mitroadmaps/roadtracer/commit/e5fda4324aa199554d29276ea03994c0a5442fbe

Without this option the MANUAL_POINT is still ignored if USE_TL_LOCATIONS=True. Instead, the code will pick a random starting point from the set of starting locations pulled from the ground truth data in starting_locations.json (generated from dataset/4_startlocs.go). It will only use one starting location though.

To use MANUAL_POINT you need to set USE_TL_LOCATIONS=False.

Regarding actual question, MANUAL_POINT should be measured from bottom left of the original tile (first coordinate is # pixel to the right of bottom left, and second is # pixel up from bottom left). But I don't know what (2560, 522) is for, I agree in Chicago it is in middle of building so doesn't seem like it was for Chicago.

Sorry for the confusion!
