### ISSUE TITLE
Is there anyway to obtain free data?

### ISSUE THREAD

**Issue by antran89** [mitroadmaps/roadtracer#21]
Hi,

I am a researcher. I wonder where can I find the free dataset to try out the roadtracer model. It seems it does not promote free research by enforcing users to pay for Google Map Platform API. Please let me know, if you find anything useful.

Best regards,
An

**Comment by uakfdotb** [comment]
I don't think you need to pay. There is $200 free credit per month Google Maps APIs (https://cloud.google.com/maps-platform/pricing/sheet/). Since Static Maps API is $2 per 1000 query, that is 100K free query. The dataset used for RoadTracer includes around 500 4096x4096 tiles, each of which require 64 queries, so that should only come to 32K queries.

A year ago they had a different pricing model where you could do 25K queries per day without even signing up an account, but even with new pricing it shouldn't require any payment.

For open dataset, there are different datasets in different countries/states. In US there is USGS High Resolution Orthoimagery (https://wiki.openstreetmap.org/wiki/USGS_High_Resolution_Orthoimagery). In Massachusetts there is also some color orthoimagery (https://docs.digital.mass.gov/dataset/massgis-data-usgs-color-ortho-imagery-20132014) which I believe is easier to download than the imagery from USGS website. EU lists several datasets (https://data.europa.eu/euodp/data/dataset?tags=Orthoimagery).

**Comment by antran89** [comment]
@uakfdotb Thank. I don't know they have $200 free credit. A good day to you.
